### ISSUE TITLE
Asking the AI Voice Assistant to tell some jokes

### ISSUE THREAD

**Issue by 0xamitdutta** [Ash515/AshTech-AI_Personal_Voice_Assistant#17] opened 2020-12-26 17:06 UTC
I think it'll be cool if you can ask the AI Voice Assistant to tell some jokes to cheer up the mood.
I think I can work on this. Kindly assign it to me.

**Comment by Amitdutta7** [comment] 2020-12-26 17:06
Hey! Can I work on this. Kindly assign it to me.

**Comment by Ash515** [comment] 2020-12-26 17:20
Yeah, nice All the very best !

**Comment by Vidura-Wijekoon** [comment] 2020-12-26 18:37
I would like to work on this issue as a part of DWOC2020. I am a beginner level student and I want to learn more about the AI with emotional intelligence by studying this issue.

**Comment by Ash515** [comment] 2020-12-27 05:25
Sure @Vidura-Wijekoon All the very best

**Comment by sahebsunny** [comment] 2020-12-27 17:08
Sir, it's an interesting idea.
if the issue is open please let me work on it

**Comment by Akashdeep-47** [comment] 2020-12-28 15:28
I would like to work on this issue. If open please let me know.

**Comment by Ash515** [comment] 2020-12-28 17:18
Yes guys @sahebsunny and @Akashdeep-47 you can start work on this issue All the very best

**Closed as completed** 2020-12-29 15:20 UTC
Labels: good first issue, DWOC, level 4
